name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Check formatting
        run: terraform fmt -check
        working-directory: terraform

      - name: Init and validate (no backend)
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: terraform
